Watching for file changes with StatReloader
Not Found: /login/
Watching for file changes with StatReloader
Not Found: /login/
Not Found: /login/
/Users/macbook/Documents/BlackJack/BlackJack/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/BlackJack/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/BlackJack/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/backends/django.py", line 109, in render
    reraise(exc, self.backend)
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/backends/django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /register/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 93, in register
    return redirect('home')
           ^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
/Users/macbook/Documents/BlackJack/blackjack_app/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 24, in game
    'balance': request.user.profile.balance,
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 531, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
/Users/macbook/Documents/BlackJack/blackjack_app/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 24, in game
    'balance': request.user.profile.balance,
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 531, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
Forbidden (CSRF token from POST incorrect.): /register/
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/views/decorators/debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/views.py", line 108, in form_valid
    auth_login(self.request, form.get_user())
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/models.py", line 24, in update_last_login
    user.save(update_fields=["last_login"])
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/base.py", line 1012, in save_base
    post_save.send(
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/models.py", line 107, in save_user_profile
    instance.profile.save()
    ^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 531, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 83, in base
    return render(request, 'base.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/template/base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static'. Did you forget to register or load this tag?
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/views/decorators/debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/views.py", line 108, in form_valid
    auth_login(self.request, form.get_user())
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/models.py", line 24, in update_last_login
    user.save(update_fields=["last_login"])
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/base.py", line 1012, in save_base
    post_save.send(
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/models.py", line 107, in save_user_profile
    instance.profile.save()
    ^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 531, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
Internal Server Error: /place_bet/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view blackjack_app.views.place_bet didn't return an HttpResponse object. It returned None instead.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 11, in game
    game, created = BlackjackGame.objects.get_or_create(user=request.user)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: dealer_hand, deck, game_over, id, player_hand
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 11, in game
    game, created = BlackjackGame.objects.get_or_create(user=request.user)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: dealer_hand, deck, game_over, id, player_hand
/Users/macbook/Documents/BlackJack/blackjack_app/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /place_bet/
Not Found: /place_bet/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
/Users/macbook/Documents/BlackJack/blackjack_app/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
Not Found: /
Watching for file changes with StatReloader
Not Found: /
Not Found: /
/Users/macbook/Documents/BlackJack/blackjack_app/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /bet/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /bet/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 48, in place_bet
    return render(request, 'blackjack_app/bet.html', {'balance': request.user.blackjackgame.balance})
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'blackjackgame'
Watching for file changes with StatReloader
Internal Server Error: /bet/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 37, in place_bet
    if request.user.profile.balance >= int(bet_amount):
       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'profile'
Watching for file changes with StatReloader
Internal Server Error: /bet/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 37, in place_bet
    if request.user.profile.balance >= int(bet_amount):
       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 531, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
Watching for file changes with StatReloader
Internal Server Error: /stay/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 61, in stay
    game = BlackjackGame.objects.get(pk=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
blackjack_app.models.BlackjackGame.DoesNotExist: BlackjackGame matching query does not exist.
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 50, in hit
    game = BlackjackGame.objects.get(pk=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
blackjack_app.models.BlackjackGame.DoesNotExist: BlackjackGame matching query does not exist.
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 50, in hit
    game = BlackjackGame.objects.get(pk=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
blackjack_app.models.BlackjackGame.DoesNotExist: BlackjackGame matching query does not exist.
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 50, in hit
    game = BlackjackGame.objects.get(pk=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
blackjack_app.models.BlackjackGame.DoesNotExist: BlackjackGame matching query does not exist.
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 50, in hit
    game = BlackjackGame.objects.get(pk=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
blackjack_app.models.BlackjackGame.DoesNotExist: BlackjackGame matching query does not exist.
Internal Server Error: /stay/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 61, in stay
    game = BlackjackGame.objects.get(pk=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
blackjack_app.models.BlackjackGame.DoesNotExist: BlackjackGame matching query does not exist.
Internal Server Error: /stay/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 61, in stay
    game = BlackjackGame.objects.get(pk=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
blackjack_app.models.BlackjackGame.DoesNotExist: BlackjackGame matching query does not exist.
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 50, in hit
    game = BlackjackGame.objects.get(pk=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
blackjack_app.models.BlackjackGame.DoesNotExist: BlackjackGame matching query does not exist.
Watching for file changes with StatReloader
Not Found: /favicon.ico
/Users/macbook/Documents/BlackJack/blackjack_app/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /place_bet/
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 29, in game
    game.player_hand = [Card(**card) for card in game_state['player_hand']]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 29, in <listcomp>
    game.player_hand = [Card(**card) for card in game_state['player_hand']]
                        ^^^^
NameError: name 'Card' is not defined
Watching for file changes with StatReloader
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 49, in hit
    result = game.player_hit()
             ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 53, in player_hit
    self.player_hand.append(self.deal_card())
                            ^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 28, in deal_card
    return self.deck.pop()
           ^^^^^^^^^^^^^^^
IndexError: pop from empty list
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 49, in hit
    result = game.player_hit()
             ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 53, in player_hit
    self.player_hand.append(self.deal_card())
                            ^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 28, in deal_card
    return self.deck.pop()
           ^^^^^^^^^^^^^^^
IndexError: pop from empty list
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 49, in hit
    result = game.player_hit()
             ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 53, in player_hit
    self.player_hand.append(self.deal_card())
                            ^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 28, in deal_card
    return self.deck.pop()
           ^^^^^^^^^^^^^^^
IndexError: pop from empty list
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 49, in hit
    result = game.player_hit()
             ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 53, in player_hit
    self.player_hand.append(self.deal_card())
                            ^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 28, in deal_card
    return self.deck.pop()
           ^^^^^^^^^^^^^^^
IndexError: pop from empty list
Internal Server Error: /stay/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 71, in stay
    result = game.dealer_play()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 61, in dealer_play
    self.dealer_hand.append(self.deal_card())
                            ^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 28, in deal_card
    return self.deck.pop()
           ^^^^^^^^^^^^^^^
IndexError: pop from empty list
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 49, in hit
    result = game.player_hit()
             ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 53, in player_hit
    self.player_hand.append(self.deal_card())
                            ^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 28, in deal_card
    return self.deck.pop()
           ^^^^^^^^^^^^^^^
IndexError: pop from empty list
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 49, in hit
    result = game.player_hit()
             ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 53, in player_hit
    self.player_hand.append(self.deal_card())
                            ^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 28, in deal_card
    return self.deck.pop()
           ^^^^^^^^^^^^^^^
IndexError: pop from empty list
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 49, in hit
    result = game.player_hit()
             ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 53, in player_hit
    self.player_hand.append(self.deal_card())
                            ^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 28, in deal_card
    return self.deck.pop()
           ^^^^^^^^^^^^^^^
IndexError: pop from empty list
Internal Server Error: /hit/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 49, in hit
    result = game.player_hit()
             ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 53, in player_hit
    self.player_hand.append(self.deal_card())
                            ^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 28, in deal_card
    return self.deck.pop()
           ^^^^^^^^^^^^^^^
IndexError: pop from empty list
Internal Server Error: /stay/
Traceback (most recent call last):
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/BlackJack/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/views.py", line 71, in stay
    result = game.dealer_play()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 61, in dealer_play
    self.dealer_hand.append(self.deal_card())
                            ^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py", line 28, in deal_card
    return self.deck.pop()
           ^^^^^^^^^^^^^^^
IndexError: pop from empty list
/Users/macbook/Documents/BlackJack/blackjack_app/game_logic.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/blackjack_app/admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /admin/edit_session_balance/
Not Found: /admin/edit_session_balance/
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
Not Found: /favicon.ico
/Users/macbook/Documents/BlackJack/slot_machine_app/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/macbook/Documents/BlackJack/slot_machine_app/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /place_bet/
Not Found: /
Not Found: /place_bet/
Watching for file changes with StatReloader
Not Found: /
Not Found: /blackjack/blackjack//place_bet/
Not Found: /blackjack/blackjack//place_bet/
Not Found: /blackjack/blackjack//place_bet/
Not Found: /blackjack/blackjack//place_bet/
Not Found: /blackjack/blackjack//place_bet/
Not Found: /blackjack/blackjack//place_bet/
Not Found: /blackjack/blackjack//place_bet/
Not Found: /blackjack/blackjack//
Watching for file changes with StatReloader
Not Found: /blackjack/blackjack/place_bet/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
